<!DOCTYPE html>
<html lang="fr">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Accueil</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="index.php">Accueil</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="/conducteur">Conducteur</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="/vehicule">Véhicule</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="/association">Association</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main>
        <h1 class="text-center mt-3">Modifier une association</h1>

        <div class="container">
            <form action="/association/edit" method="POST">
                <input type="hidden" name="association-id" value="<?=$association['id_association'];?>">
                <fieldset>
                    <div class="form-group">
                        <label for="conducteur">conducteur</label>
                        <select name="conducteur" required>
                            <?php foreach ($associations as $association): ?>
                                <?php $conducteurId = $_POST['id_conducteur']??$product['id_conducteur']; ?>
                                <?php $selected = $association['id_association'] == $conducteurId ? 'selected' : ''; ?>
                                <option <?=$selected;?> value="<?=$association['id_association'];?>"><?=$association['prenom'];?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group mt-2">                   
                        <label for="conducteur">vehicule</label>
                        <select name="vehicule" required>
                            <?php foreach ($associations as $association): ?>
                                <?php $vehiculeId = $_POST['id_vehicule']??$product['id_vehicule']; ?>
                                <?php $selected = $association['id_association'] == $vehiculeId ? 'selected' : ''; ?>
                                <option <?=$selected;?> value="<?=$association['id_association'];?>"><?=$association['marque'];?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </fieldset>
                <input type="submit" value="Enregistrer" class="btn btn-dark mt-2">
            </form>
        </div>
    </main>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</body>

</html>