<!DOCTYPE html>
<html lang="fr">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Accueil</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="index.php">Accueil</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="/conducteur">Conducteur</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="/vehicule">Véhicule</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="/association">Association</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main>
        <h1 class="text-center mt-3">Page d'accueil</h1>


        <!-- Plus assez de temps donc j'ai fais le max comme je pouvais même si je sais que c'était pas forcément ce qui étais attendu ... -->
        <div class="container">
            <p>Afficher le nombre de conducteur : <?= implode(', ', $nbConducteurs); ?></p>
            <p>Afficher le nombre de véhicules : <?= implode(', ', $nbVehicules); ?></p>
            <p>Afficher le nombre d'associations : <?= implode(', ', $nbAssociations); ?></p>
            <p>Afficher les véhicules n'ayant pas de conducteurs : <?php foreach ($vehiculesansconducteur as $vehicule) : ?> <?= implode(', ',$vehicule); ?>,<?php endforeach ?></p>
            <p>Afficher les conducteurs n'ayant pas de véhicules : <?php foreach ($conducteursansvehicule as $conducteur) : ?> <?= implode(', ',$conducteur); ?>,<?php endforeach ?></p>
            <p>Afficher les véhicules conduit par Phillipe Pandre : <?php foreach ($vehiculePhillipe as $vehicule) : ?> <?= implode(', ',$vehicule); ?>,<?php endforeach ?></p>
            <p>Afficher tous les conducteurs et leurs véhicules : <?php foreach ($conducteurandvehicule as $conducteur) : ?> <?= implode(', ',$conducteur); ?>,<?php endforeach ?></p>
        </div>
    </main>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</body>

</html>